# Generated by Django 4.2 on 2023-04-12 07:10

import create_hack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateHack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('background_image', models.ImageField(upload_to=create_hack.models.upload_background_image)),
                ('hack_image', models.ImageField(upload_to=create_hack.models.upload_hack_image)),
                ('type_of_submission', models.CharField(choices=[('image', 'image'), ('file', 'file'), ('link', 'link')], max_length=5)),
                ('start_date', models.DateTimeField(editable=False)),
                ('end_date', models.DateTimeField(editable=False)),
                ('reward_prize', models.CharField(max_length=500)),
            ],
        ),
    ]
