# Generated by Django 4.2 on 2023-04-12 07:22

import create_hack.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_hack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhack',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to=create_hack.models.upload_background_image),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='hack_image',
            field=models.ImageField(blank=True, null=True, upload_to=create_hack.models.upload_hack_image),
        ),
    ]
