# Generated by Django 4.2 on 2023-04-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_hack', '0002_alter_createhack_background_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhack',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='end_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='reward_prize',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='start_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='type_of_submission',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('file', 'file'), ('link', 'link')], max_length=5, null=True),
        ),
    ]
