# Generated by Django 4.2 on 2023-04-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_hack', '0003_alter_createhack_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createhack',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='createhack',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
