# Generated by Django 4.2 on 2023-04-13 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register_submit_hack.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('create_hack', '0004_alter_createhack_end_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResigterHack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hackathon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_hack.createhack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=register_submit_hack.models.upload_cover_image)),
                ('submission_link', models.CharField(blank=True, max_length=200, null=True)),
                ('submission_image', models.ImageField(blank=True, null=True, upload_to=register_submit_hack.models.upload_submission_image)),
                ('submission_file', models.FileField(blank=True, null=True, upload_to=register_submit_hack.models.upload_submission_file)),
                ('registered_hack', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='register_submit_hack.resigterhack')),
            ],
        ),
    ]
